import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthContext } from './AuthContext';
import { Providers } from '@/app/providers';
import { Navbar } from '@/components/navbar/Navbar';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={'text-dark-brown max-w-screen bg-pastel-beige'}>
      <body className={inter.className}>
        <AuthContext>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </AuthContext>
      </body>
    </html>
  );
}
