name: Frontend
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps
        working-directory: ./frontend
        run: |
          npm install
      - name: Format check
        working-directory: ./frontend
        run: |
          npm run fmt-check
